# Generated by Django 4.1.7 on 2023-03-07 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=12, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('branchNDyear', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('waPhone', models.BigIntegerField()),
                ('paper', models.BooleanField(default=False)),
                ('poster', models.BooleanField(default=False)),
                ('debugging', models.BooleanField(default=False)),
                ('expo', models.BooleanField(default=False)),
                ('quiz', models.BooleanField(default=False)),
                ('treasure', models.BooleanField(default=False)),
                ('short', models.BooleanField(default=False)),
                ('conn', models.BooleanField(default=False)),
                ('circuit', models.BooleanField(default=False)),
                ('tinker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startyear', models.PositiveIntegerField(default=2020)),
                ('dob', models.DateField(auto_now_add=True)),
                ('branch', models.CharField(default=False, max_length=8)),
                ('rollno', models.CharField(default=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('cash', models.BooleanField(default=False)),
                ('verifiedBy', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
    ]
