# Generated by Django 4.1.7 on 2023-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='shark',
            field=models.BooleanField(default=False),
        ),
    ]
