# Generated by Django 4.1.7 on 2023-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_branchndyear_student_branchnyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verifiedBy',
            field=models.CharField(default='#', max_length=12),
        ),
    ]
