# Generated by Django 4.1.7 on 2023-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
